BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "UsersMistakes" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"UserId"	INTEGER NOT NULL,
	"FunctoinId"	INTEGER NOT NULL,
	"Mistakes"	INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "Users" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"User"	TEXT NOT NULL UNIQUE,
	"Payment"	INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS "Functions" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Description"	TEXT
);
COMMIT;
